// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5Px3Tpi00SErk4dD3Fk_mWgaHTpGoF8',
    appId: '1:332370573395:web:f00056d54fb9b1c2de2ea6',
    messagingSenderId: '332370573395',
    projectId: 'jobmitra-309cb',
    authDomain: 'jobmitra-309cb.firebaseapp.com',
    storageBucket: 'jobmitra-309cb.firebasestorage.app',
    measurementId: 'G-J726LHEPFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-U68urhePIoyXZCw2dUHYwsdn1R5Xz4',
    appId: '1:332370573395:android:d8e86f4a74ef6539de2ea6',
    messagingSenderId: '332370573395',
    projectId: 'jobmitra-309cb',
    storageBucket: 'jobmitra-309cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCLB9T1DioFLIZCzn1aQ-UfZolNB3f9M',
    appId: '1:332370573395:ios:af1a67e972a1b4fade2ea6',
    messagingSenderId: '332370573395',
    projectId: 'jobmitra-309cb',
    storageBucket: 'jobmitra-309cb.firebasestorage.app',
    iosBundleId: 'com.example.laborlane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCLB9T1DioFLIZCzn1aQ-UfZolNB3f9M',
    appId: '1:332370573395:ios:af1a67e972a1b4fade2ea6',
    messagingSenderId: '332370573395',
    projectId: 'jobmitra-309cb',
    storageBucket: 'jobmitra-309cb.firebasestorage.app',
    iosBundleId: 'com.example.laborlane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP5Px3Tpi00SErk4dD3Fk_mWgaHTpGoF8',
    appId: '1:332370573395:web:5f8a00dfa98fedb4de2ea6',
    messagingSenderId: '332370573395',
    projectId: 'jobmitra-309cb',
    authDomain: 'jobmitra-309cb.firebaseapp.com',
    storageBucket: 'jobmitra-309cb.firebasestorage.app',
    measurementId: 'G-SXF0CHHZC8',
  );
}
